### ISSUE TITLE
Issue when trying to build the Blast database

### ISSUE THREAD

**Issue by RNiloP** [GGFHF/TOA#5]
Hi, when running the step "Main menu > Genomic databases > NCBI BLAST database NR > Build BLAST database [Execute]" (page 19 of the manual) I had the following issue:

"Starting TOA (Taxonomy-oriented Annotation) v0.66 ...
Please, press [Ctrl] to continue  ...
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ranp_u/TOA-master/Package/xtoa.py", line 1144, in manage_genomic_database
    log.write('This process might take several minutes. Do not close this window, please wait!\n')
  File "/home/ranp_u/TOA-master/Package/gdialogs.py", line 690, in write
    self.log_file_id.flush()
OSError: [Errno 28] No space left on device"

I am using Windows WSL2, and Ubuntu 20.04 LTS

Here are the specifics of the machine I am running:
OS Name:                   Microsoft Windows 11 Home
OS Version:                10.0.22000 N/A Build 22000
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
System Model:              HP Desktop M01-F1xxx
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: AMD64 Family 23 Model 96 Stepping 1 AuthenticAMD ~3600 Mhz
BIOS Version:              AMI F.21, 9/17/2021
Total Physical Memory:     32,132 MB
Available Physical Memory: 19,368 MB
Virtual Memory: Max Size:  36,996 MB
Virtual Memory: Available: 21,452 MB
Virtual Memory: In Use:    15,544 MB 

All the previous steps could be performed without any issues.

Many thanks

Ricardo

**Comment by fernandomoramarquez** [comment]
Hi Ricardo:

First, thanks for using TOA and your input.

The NR database needs a large amount of free space on your disk because for its building is necessary to download 56 files of several GB each one. The error mesage "OSError: [Errno 28] No space left on device" is possibly due to the fact that the device where the database directory is located does not have the necessary free space. Can you please check the free space?

On the other hand, we have not yet tested TOA on Windows 11 WSL2. Can you tell us if the appearance of this application is similar to the figures that appear in the manual and how is its performance?

All the best,

**Comment by RNiloP** [comment]
Dear Fernando

thank you for the make available this great tool and for the kind answer.

Is there a way to allocate the disk space required by this database to an external (D:) disk? This disk has 3 TB of free disk space memory.

So far all the previous steps have been working as seem in the pdf manual.

Thanks!

Ricardo

**Comment by fernandomoramarquez** [comment]
Dear Ricardo:

The solution is to move the directory where the local data of genomic databases are located from the hard disk (C:) to the external disk (D:). In the menu-item "Main menu > Configuration > Recreate TOA config file" is the field "Database directory" which holds the current directory path. First, move this directory from C to D and then, modify the field  "Database diretory" with the new path.

The use of an external disk will significantly degrade the performance of databases building processes and annotation pipelines runs.

All the best,

**Comment by RNiloP** [comment]
Dear Fernando

I have been able to solve the issue with the disk size by incrementing the WSL2 limit from 256 GB to 400 GB (https://docs.microsoft.com/en-us/windows/wsl/vhd-size). Many thanks for the help!
